title: Minh Hoang Nguyen
description: Researcher in AI focusing on Reinforcement Learning and intelligent agents
theme: minima

header_pages:
  - cv.md
  - experience.md
  - publications.md
  - awards.md
  - contact.md
